package com.devicehive.model.rpc;

public enum Action {
    ERROR_RESPONSE,

    ECHO_REQUEST,
    ECHO_RESPONSE,

    NOTIFICATION_SEARCH_REQUEST,
    NOTIFICATION_SEARCH_RESPONSE,
    NOTIFICATION_INSERT,
    NOTIFICATION_SUBSCRIBE_REQUEST,
    NOTIFICATION_SUBSCRIBE_RESPONSE,
    NOTIFICATION_UNSUBSCRIBE,
    NOTIFICATION,

    COMMAND_SEARCH_REQUEST,
    COMMAND_SEARCH_RESPONSE,
    COMMAND_INSERT_REQUEST,
    COMMAND_INSERT_RESPONSE,
    COMMAND_SUBSCRIBE,
    COMMAND_UNSUBSCRIBE,
    COMMAND
}
